name: publish to nuget
on:
  push:
    branches:
      - main # Default release branch, may also be named 'master' or 'develop'
    paths:
      - '**.cs*'

env:
  project: Oceyra.Dbml.Parser
  path_to_project: src/Oceyra.Dbml.Parser/Oceyra.Dbml.Parser.csproj
  path_to_test_project: src/Tests/Oceyra.Dbml.Parser.Tests/Oceyra.Dbml.Parser.Tests.csproj

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Restore dependencies
        run: dotnet restore $path_to_test_project

      - name: Build solution and generate NuGet package
        run: dotnet build $path_to_test_project --configuration Release

      - name: Run unit tests with report
        run: dotnet test $path_to_test_project --configuration Release --no-build --logger "trx;LogFileName=TestResults.trx" --results-directory "TestResults"

      - name: Test Report
        uses: dorny/test-reporter@v2
        if:  ${{ !cancelled() }}            # run this step even if previous step failed
        with:
          name: Xunit Tests                 # Name of the check run which will be created
          path: TestResults/TestResults.trx # Path to test results
          reporter: dotnet-trx              # Format of test results

  publish:
    name: Pack & Publish
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Build solution and generate NuGet package
        run: dotnet pack $path_to_project -p:Version=0.7.${{ github.run_number }} --configuration Release --output bin  

      - name: Push generated package to Local registry
        if: ${{ vars.nuget_api_url != '' }}
        run: dotnet nuget push bin/*.nupkg --source ${{ vars.nuget_api_url }} --skip-duplicate --no-symbols --api-key ${{ secrets.nuget_api_key }} --version-suffix Beta

      - name: Push generated package to Nuget registry
        if: ${{ vars.nuget_api_url == '' }}
        run: dotnet nuget push bin/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols --api-key ${{ secrets.nuget_api_key }}
